SocialApplication/Controllers/IdentityController.cs
using SocialApplication.Models;
using SocialApplication.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using SocialApplication.Models.ViewModels;
using System.Threading.Tasks;
using SocialApplication.Models.Filters;

namespace SocialApplication.Controllers
{
    public class IdentityController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;
        public ApplicationUserManager userManger { set { this._userManager = value; } get { return this._userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); } }
        public ApplicationSignInManager signInManager { set { this._signInManager = value; } get { return this._signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();  } }
        [NoAuthenticatedOnly]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [NoAuthenticatedOnly]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result=signInManager.PasswordSignIn(model.Email, model.password, model.IsRemember, false);
                if (result == SignInStatus.Success)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("error", "Your account is something worng");
            }
            return View(model);
        }
        [HttpGet]
        [NoAuthenticatedOnly]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [NoAuthenticatedOnly]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser()
                {
                    UserName=model.Email,
                    Email=model.Email,
                };
                var result=await userManger.CreateAsync(user,model.password);
                if (result.Succeeded)
                {
                    using (Context context = new Context())
                    {
                        Profile profile = new Profile()
                        {
                            UserId = user.Id,
                            DisplayName = Guid.NewGuid().ToString(),
                            Date_Of_Birth=DateTime.Now
                        };
                        context.profiles.Add(profile);
                        context.SaveChanges();
                    }
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("error", "Your account is something worng");
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult LogOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

SocialApplication/Views/Shared/_AbstractBlogCard.cshtml
@model BlogViewModel


<div class="row position-relative row mx-2 h-100 g-3 justify-content-center mb-2">
    <div class="col-md-9 col-12 mx-2 px-2">
        <div class=" row row-cols-1">
            <div class="card rounded-2 p-2 shadow-sm">
                <div class="p-1 m-1 mb-2">
                    <div class="d-flex">
                        <div class="fw-bold fs-5">
                            @Html.ActionLink(Model.Name, "Index", new { controller = "Profile", id = Model.ProfileId }, new { @class = "text-decoration-none text-dark h4 mb-2" })
                        </div>
                        <div class="dropdown ms-auto">
                            <button class=" dropdown-toggle btn btn-light w-100" type="button" id="dropdownmenu" data-bs-toggle="dropdown" aria-expanded="false">

                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownmenu">
                                @Html.ActionLink("Save", "Save", new { controller = "Blog", id = Model.Id }, new { @class = "dropdown-item" })

                                @if (User.Identity.Name == @Model.AuthorEmail)
                                {
                                    @Html.ActionLink("Update", "Update", new { controller = "Blog", id = Model.Id }, new { @class = "dropdown-item" })
                                    <a asp-action="Update" asp-controller="Blog" asp-route-Id=@Model.Id class="dropdown-item">Update</a>
                                    <span class="dropdown-divider"></span>
                                    using (Html.BeginForm("Delete", "Blog", new { id = Model.Id }, FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <input class="dropdown-item" type="submit" role="button" value="Delete">
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>

                <a href='@Url.Action("Detail","Blog",new { id=Model.Id })' class="text-decoration-none text-dark">
                    <div class="px-3 py-1">
                        @if (Model.GetUrl() != null)
                        {
                            <img src="@Url.Content(Model.GetUrl())" width="700" class="img-fluid m-auto d-block mb-2">
                        }
                    </div>
                    <div class="card-body mb-1 text-wrap">
                        <article class='m-1'>
                            @Model.Title
                        </article>
                        <article class='m-1 p-1 text-truncate'>
                            @Model.Content
                        </article>
                    </div>
                </a>
                @if (Model.liked == false)
                {
                    <div class="px-2 border-top border-1 border-dark">
                        @Html.ActionLink($"{Model.reactionCount}Like", "Like", new { controller = "Reaction", id = Model.Id }, new { @class = "fs-6 m-1 pt-3 pb-2 text-dark text-decoration-none" })
                    </div>
                }
            </div>
            <!-- this is card -->
        </div>
    </div>
    <!-- this is row -->

</div>

SocialApplication/Views/Shared/_BlogCard.cshtml
@model BlogViewModel

<div class="m-2 px-3 w-75 m-auto">
    <div class="d-block float-end position-relative">
        @if (Model.AuthorEmail == User.Identity.Name)
        {
            <a asp-action="Update" asp-controller="Blog" asp-route-Id=@Model.Id class="btn btn-warning">Update</a>
            using (Html.BeginForm("Delete", "Blog", new { id = Model.Id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <input class="btn btn-danger" type="submit" role="button" value="Delete">
            }
        }
    </div>
    <div class="p-2 mx-2">
        @Html.ActionLink(Model.Name, "Index", new { controller = "Profile", id = Model.ProfileId }, new { @class = "text-decoration-none text-dark h4 mb-2" })


    </div>
    @if (Model.GetUrl() != null)
    {
        <img src="@Url.Content(Model.GetUrl())" width="700" class="img-fluid m-auto d-block mb-2">
    }


    <div class="p-2 mx-2">
        <div class='p-1 m-1 h5'>
            @Model.Title
        </div>
        <p class="p-2 m-1 ">
            @Model.Content
        </p>
        <div class="pt-2 pb-1 border-top border-1 my-2">
            @Html.ActionLink($"{Model.reactionCount}Like", "Like", new { controller = "Reaction", id = Model.Id }, new { @class = "fs-6 m-1 pt-3 pb-2 text-dark text-decoration-none" })
        </div>
    </div>
</div>

SocialApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - communicator</title>
    @Styles.Render("~/Content/css")
</head>

<body class="">
    <header class="p-1">
        <nav class="p-1 navbar navbar-light navbar-expand-lg bg-light">
            <div class="navbar-brand fs-4 mb-1">
                Communicator
            </div>
            <button type="button" class="navbar-toggler" data-bs-target="#navrealpart" data-bs-toggle="collapse" aria-controls="navrealpart" aria-expanded="false" aria-labelledby="navrealpart">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navrealpart">
                <ul class="navbar-nav ms-auto ">
                    <li class="navbar-item mx-1 p-1">@Html.ActionLink("Home", "Index", new { controller= "Home" }, new { @class = "nav-link text-decoration-none" })</li>
                    <li class="navbar-item mx-1 p-1">@Html.ActionLink("Blog", "Index", new { controller = "Blog" }, new { @class = "nav-link text-decoration-none" })</li>
                    <li class="navbar-item mx-1 p-1">@Html.ActionLink("About", "About", new { controller = "Home" }, new { @class = "nav-link text-decoration-none" })</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class='nav-item'>
                            <div class='dropdown'>
                                <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                        id="nav-dropdown">
                                    @User.Identity.Name
                                </button>
                                <ul class='dropdown-menu w-100' aria-labelledby="nav-dropdown">
                                    <li>
                                        @Html.ActionLink("Profile", "Index", new { controller= "Profile" }, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @Html.ActionLink("Saved Posts", "Index", new { controller="Save" }, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @Html.ActionLink("Show Friends", "Index", new { controller = "Friend" }, new { @class = "dropdown-item" })
                                    </li>
                                    <li>
                                        @using (Html.BeginForm("Logout", "Identity", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()
                                            <input type="submit" class="dropdown-item" value="Sign Out">
                                        }
                                    </li>
                                </ul>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class='navbar-item mx-2 p-1'>
                            @Html.ActionLink("Login", "Login", new { controller = "Identity" }, new { @class = "btn btn-primary" })
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container container-main">
        <main role="main" class="pb-3 min-vh-75 main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            &copy; 2022 - communicator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

SocialApplication/Views/Shared/_SaveCard.cshtml
@model SaveViewModel

<div class="row border-1 border rounded-1 w-75 m-auto m-0 p-0">
    <div class="col-12 col-lg-4">
        <img src="./template.jpg" class="img-fluid p-1 ">
    </div>
    <div class="col p-2">

        <div class="p-2 m-1 px-3">
            <div class="mb-1">
                <a asp-action="Index" asp-controller="Profile" asp-route-id=@Model.ProfileId class="text-decoration-none text-dark">@Model.Name</a>
            </div>
            <div class="mb-1">
                <span>Created At:</span>
                <span>@Model.BlogCreatedAt</span>
            </div>
            <div>
                @Html.ActionLink("ReadMore","Detail",new { controller="Blog",id=Model.BlogId }, new { @class="btn btn-primary"})
                @Html.ActionLink("Unsave","UnSave",new { controller="Save",id=Model.BlogId }, new { @class="btn btn-warning"})
            </div>
        </div>
    </div>
</div>